### ISSUE TITLE
Error while running make

### ISSUE THREAD

**Issue by techierishi** [ec429/libatg#2]
process_begin: CreateProcess(NULL, sh C:\MinGW\bin\libtool --mode=compile gcc -Wall -Wextra -Werror -pedantic --std=gnu99 -g -DMONOFONTP
 -name LiberationMono-Regular.ttf -print -quit)\" `sdl-config --cflags` -c atg.c, ...) failed.
make (e=2): The system cannot find the file specified.
make: **\* [atg.lo] Error 2

**Comment by ec429** [comment]
Aaaaand coming back and looking at this years later I notice that you were building this on Windows, so `/usr/share/fonts` isn't a thing that exists.
I haven't ever tried building on Windows (I cross-compile Windows builds from Linux, see the `wbits/` folder), but I think you probably want to `-DWINDOWS` in the CFLAGS and not set MONOFONTPATH at all (then make sure to include LiberationMono-Regular.ttf with the application); see `w_label.c` for how that fits together.
